server:
  port: 1111 #8888

eureka:
  server:
     enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
     #eviction-interval-timer-in-ms: 1000 # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  #设置是否将自己作为客户端注册到注册中心（缺省true）
     
    fetchRegistry: false #设置是否从注册中心获取注册信息（缺省true）
    serviceUrl:
       # 实际测试：若修改尾部的eureka为其它的，比如/myeureka，注册中心启动没问题，但服务端在注册时会失败
      # 报告异常：com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
      defaultZone: http://localhost:1111/eureka/
      

    

