server:
  port: 2300
spring:
  application:
    name: zuul-service
eureka: 
  client: 
    serviceUrl:
       # 实际测试：若修改尾部的eureka为其它的，比如/myeureka，注册中心启动没问题，但服务端在注册时会失败
      # 报告异常：com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
      defaultZone: http://localhost:8888/eureka/

zuul:
  routes:
    api-a: 
      path: /api-provider/**
      service-id: provider-service
    api-b:
      path: /api-consumer/**
      service-id: consumer-service
      

    

